# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TextureAnalyzer
                                 A QGIS plugin
 Procura identificar as texturas presentes em um dado conjuntos de imagens raster.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-02
        copyright            : (C) 2019 by Givaldo Cesar/DECart/UFPE
        email                : givaldocesar@live.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TextureAnalyzer class from file TextureAnalyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .texture_analyzer import TextureAnalyzer
    return TextureAnalyzer(iface)
